AdevintaSpain/Barista

- README.md
As most projects use the Support Library, if we don't exclude it from the Barista dependency, the app version and the Barista one will conflict. Excluding it from Barista at the readme showcases this issue and the solution. If someone prefer to fix the issue by another way, they will be free to remove the exclude line and do their preferred magic.
> Improve the Gradle compile line excluding Support Library

- README.md
- library/build.gradle
- library/src/main/AndroidManifest.xml
- library/src/main/java/com/schibsted/spain/barista/permission/PermissionGranter.java
As Barista is the last and better way to solve instrumental tests issues, we want to solve the issue related with allowing permissions with the system dialog. As Espresso can't tap that Dialog 'cause it's not an app one but a system one, we need to add UiAutomator.
> Add PermissionGranter to Barista

- README.md
- library/src/main/java/com/schibsted/spain/barista/cleardata/ClearPreferencesRule.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClearPreferencesRuleTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/PreferencesActivity.java
- sample/src/main/res/layout/activity_preferences.xml
This rule lets us clear all preferences from the app between each test method. This way they are independent of any side-effects happening in any test.
TODO:
> Clear preferences test rule

- README.md
@Sloy don't know why, readme was showing `## Dealing with Flaky tests` instead of <b>Dealing with Flaky tests</b>. This PR just removes your ## and retype it with my brand new bluetooth mac keyboard. It seems that my keyboard is better than yours 🌟
> Fix a ## tag on readme

- .travis.yml
- scripts/build.sh
Using dry run and fake auth, of course.
This solves the problems found at #34, where some tasks are only run when releasing and might fail after a new PR has been merged already.
The original idea was to run the task that failed in my case (`: library:mavenAndroidJavadocs`), but I think using the dryRun feature of the publishing plugin is better. This way we make sure all release tasks are executed except for the upload itself.
> Run upload task on PRs also

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaRadioButtonActions.java
- library/src/main/java/com/schibsted/spain/barista/custom/HelperMatchers.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/RadioButtonsTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaActions.java
Here it comes! @Sloy as I needed a place to add Matchers, I used your class `HelperMatchers` at #38 . So, you will just add a method to that class if this PR is merged faster than yours :·)
By the way, the matcher this PR adds could be very useful for other tasks at Barista.
> Add a method to click a radio button by position

- README.md
- library/build.gradle
- library/src/main/java/com/schibsted/spain/barista/cleardata/ClearDatabaseRule.java
- library/src/main/java/com/schibsted/spain/barista/cleardata/DatabaseOperations.java
- library/src/test/java/com/schibsted/spain/barista/cleardata/DatabaseOperationsTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClearDatabaseRuleTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/DatabaseActivity.java
- sample/src/main/res/layout/activity_database.xml
This Rule works similarly to #24, but for SQLite databases.
It fetches all databases in the app, obtains all tables from them, and performs a "delete from" [without where](https://www.youtube.com/watch?v=i_cVJgIz_Cs).
I decided to do this instead of a DROP because I think it might break the app, not sure though.
This should be tested against different scenarios and sdk versions. I've seen in [Stetho](https://github.com/facebook/stetho/blob/master/stetho/src/main/java/com/facebook/stetho/inspector/database/DefaultDatabaseConnectionProvider.java) that they have different ways of opening databases depending on the sdk version. Wonder why.
TODO:
> Clear Database Test Rule

- library/src/main/java/com/schibsted/spain/barista/BaristaAssertions.java
- library/src/main/java/com/schibsted/spain/barista/custom/HelperMatchers.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/main/res/layout/activity_main.xml
- sample/src/main/res/values/strings.xml
This is a solution proposal for #37 
The trick is to combine `firstViewOf()` with `allOf()`, and include the verification as a condition.
Yeah, that crazy. But it should work.
> Accept repeated views

- library/src/main/java/com/schibsted/spain/barista/custom/PerformClickAction.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/RecyclerViewTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/WrappedViewClickTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/RecyclerViewActivity.java
- sample/src/main/java/com/schibsted/spain/barista/sample/WrappedViewActivity.java
- sample/src/main/res/layout/activity_wrapped_view.xml
This PR fixes the issue in #47.
On PR #40 we introduced a change to avoid clicking wrong things in a RecyclerView row, and allow clicking child views inside a row.
Unfortunately, that last change also broke the click when the ClickListener is set in a child view and not directly in the ItemView, as described in #47.
In this PR we:
- Reproduce the issue with a broken test (`WrappedViewClickTest`).
- Fix some flaky tests on RecyclerViewTest that were already giving false positives.
- Fix the original issue by **only** using `performClick()` when the view is clickable, or else use Espresso's `click()` action to allow propagating the click as usual.
> Fixes click on RecyclerView when ItemView is wrapped

- library/src/main/java/com/schibsted/spain/barista/BaristaRecyclerViewActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/RecyclerViewInsideViewPagerTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/RecyclerViewsInsideViewPagerActivity.java
This PR just reproduces this issue https://github.com/SchibstedSpain/Barista/issues/49 and fixes it.
Thanks again for reporting it, @despinola !
> Reproduce issue #49 and fix it

- library/src/main/java/com/schibsted/spain/barista/BaristaRadioButtonActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/RadioButtonsReallyFarAwayTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/RadioButtonsActivity.java
- sample/src/main/res/layout/activity_radiobuttons.xml
As we explained at #52 , Barista is intended to scroll everytime is needed. But looking at tests and code, we noticed that it wasn't happening when clicking a RadioButton item.
This PR adds tests to check it and implements the solution of those tests.
Fixes #54
> Autoscroll on RadioButtonsAction

- README.md
- library/build.gradle
- library/src/main/java/com/schibsted/spain/barista/BaristaViewPagerActions.java
- library/src/main/java/com/schibsted/spain/barista/custom/DisplayedMatchers.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ViewPagerWithoutIdTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaActions.java
The original idea? Look here! #8
> Create methods to avoid knowing the ID of the ViewPager if there's only one ViewPager

- .travis.yml
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
Android Studio warned me about living in the past. This PR fixes it.
In addition, as one build crashed while waiting for an emulator (that we don't use yet), this PR also avoids waiting for it.
> Update gradle and Build Tools

- library/src/main/java/com/schibsted/spain/barista/BaristaClickActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ButtonsTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClickInsideViewPagerTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ViewPagerTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ViewPagerWithoutIdTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/RadioButtonsActivity.java
- sample/src/main/java/com/schibsted/spain/barista/sample/ViewPagerButtonFragment.java
- sample/src/main/java/com/schibsted/spain/barista/sample/ViewPagerWithFiveSamePagesActivity.java
- sample/src/main/java/com/schibsted/spain/barista/sample/ViewPagerWithTwoDifferentPagesActivity.java
- sample/src/main/res/layout/activity_centered_button.xml
- sample/src/main/res/layout/activity_flow_1.xml
- sample/src/main/res/values/strings.xml
As #62 explains, the autoscroll magic stopped working. We think that it happened at #51.
This PR reproduces the issue and fixes it.
But... it creates a new issue: it breaks the feature added at #51. So, we also test it and fix it.
> Check that click() scrolls when needed

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaAssertions.java
- library/src/main/java/com/schibsted/spain/barista/BaristaRecyclerViewActions.java
- library/src/main/java/com/schibsted/spain/barista/BaristaSwipeRefreshActions.java
- library/src/main/java/com/schibsted/spain/barista/custom/CustomConstraintViewAction.java
- library/src/main/java/com/schibsted/spain/barista/custom/RecyclerViewItemCountAssertion.java
- library/src/main/java/com/schibsted/spain/barista/custom/SwipeRefreshActions.java
- sample/build.gradle
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/RecyclerViewTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/SwipeRefreshTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaAssertions.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/RecyclerViewActivity.java
- sample/src/main/java/com/schibsted/spain/barista/sample/SwipeRefreshActivity.java
- sample/src/main/res/layout/activity_swipe_refresh.xml
- sample/src/main/res/values/strings.xml
Added new `RecyclerView` action, comparing actual `RecyclerView` item count against expected item count. This is very useful when testing RecyclerView dataset count changes or complete refreshing. E.g. helps testing when datalist should be completely refreshed but instead it duplicates items.
Added Pull-To-Refresh action for the `SwipeRefreshLayout`.
Added new `ViewAction` that supports custom constraints. This is helpful when writing tests for `SwipeToRefresh` that is slightly obscured, since espresso internally requires views to be visible at least 90%.
Added tests for new features above.
> RecyclerView and SwipeRefreshLayout actions

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaRule.java
This rule includes all other rules, so it's easier and simpler to write tests without boilerplate.
It assumes sane defaults, and doesn't really allow customisation. Whoever wants to do something different, they can use the individual rules instead. Defaults are:
- Flaky attempts (without annotation): 10
- Launch activity automatically: false
- Initial touch mode enabled: true
- Clear preferences: always
- Clear databases: always
I wasn't sure how to add tests for it... Repeating the same tests that all rules have it's a lot of duplication. And I don't know how to test that a rule includes other rules.
I just tested manually by changing the current rules tests and replacing the original rules with this one.
It works.
This solves #26
TODO:
> Create BaristaRule to rule them all

- library/src/main/java/com/schibsted/spain/barista/BaristaSleepActions.java
- library/src/main/java/com/schibsted/spain/barista/permission/PermissionGranter.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/PermissionGranterTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/RuntimePermissionActivity.java
- sample/src/main/res/layout/activity_runtime_permission.xml
We were using a sleep() which uses a ViewAction to make a magic efficient sleep. But since the permission dialog is on top of the application, Espresso cannot run the ViewAction.
Soooo changing it to a Thread.sleep() that doesn't require any view makes it work.
This fixes #61 and probably #74
> Fix permission granter

- library/src/main/java/com/schibsted/spain/barista/permission/PermissionGranter.java
The PermissionGranter class is annotated with RequiresApi 18 (because UI automator requires that api level).
This means that using PermissionGranter in an application that supports APIs lower than 18, Lint will give an error.
But in sdks lower than 23 we don't even use UiAutomator because permissions are granted at install time, so we're actually fine.
This PR removes the annotation so that we don't mislead the user.
I've tried running the PermissionGranter test on an emulator with api 17 and it works just fine.
> Remove api limit to PermissionGranter

- library/src/main/java/com/schibsted/spain/barista/BaristaClickActions.java
Since `BaristaClickActions.click()` supports both `R.id` and `R.string` we don't need anymore the `@IdRes` annotation
> Remove @IdRes from click() actions

- library/src/main/java/com/schibsted/spain/barista/flakyespresso/AllowFlakyStatement.java
When using the @AllowFlaky rule or similar, Barista retries the test several times to see if it pass sometime.
At each attempt we print a log telling which attempt are we starting and the result of each one.
Since Espresso is so flaky and so many different things can go wrong, while debugging tests it can be helpful to
see what error caused each failed attempt.
This PR adds the stacktrace of the exception to the log.
This is how it looks like:
> Add stacktrace to log on failed flaky attempts

- sample/src/androidTest/java/com/schibsted/spain/barista/sample/PermissionGranterTest.java
In order to reproduce the issue #108, I ran the tests on my emulator. Two tests failed requesting me to clear the data. And I cleared the data. But the tests were failing.
Actually, they were failing because the emulator I was using was on Android 21, and it doesn't have the runtime permissions system.
With this PR, when running the tests on Android 22 or below, a message will explain that the tests fill wail on Android 22 or below. WOW! Rockets there 🚀
> Improve the explanation when the PermissionsDialog tests fail

- library/src/main/java/com/schibsted/spain/barista/permission/PermissionGranter.java
See #108 
Is the fist time I submit a pull request, hope I'm not messing up the things :s
> The selector for the allow button use the resourceId instead of the index

- .travis.yml
- README.md
- build.gradle
- library/build.gradle
- library/src/main/java/com/schibsted/spain/barista/custom/AutocompleteViewActions.java
- sample/build.gradle
I had to update the support library from 25.1.0 to 25.4.0, and change how we exclude some transitive dependencies.
I had to add the new Google Maven repository, where Espresso 3 is published.
I extracted all shared versions (libraries and sdks) to the main gradle file, because it was a nightmare trying to sync all versions from the library and sample.
This way future changes will be less painful.
With the migration to Espresso 3 there was just one code compilation error, because Espresso changed its included Guava package.
> Update to Espresso 3

- config/findbugs/findbugs-excludes.xml
This needs to happen.
Kotlin generates code that doesn't make findbugs happy, but we don't care about his feelings,
we like Kotlin better. He's the new kid in the hood and we're friends.
No, really. We've done 2 PRs with kotlin code and findbugs failed in both because of the bytecode generation.
It's not helpful for kotlin files.
> Exclude kotlin files from Findbugs

- library/src/main/java/com/schibsted/spain/barista/BaristaClickActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClickInsideViewPagerTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/ViewPagerButtonFragment.java
- sample/src/main/res/layout/activity_centered_button.xml
- sample/src/main/res/values/strings.xml
This magic behavior of the click method was implemented, but didn't have any test covering it.
And guess what. It didn't work!
The `scrollAndClickDisplayedView` was using the `isDisplayed` condition to filter the button from the current viewpager. But since the button is below a scroll, isDisplayed would never match.
I created the missing test to reproduce it, and fixed the method by using a more complex view matcher. The `isDisplayed` filter is applied on the scrollable ancestor of the button, and not the button itself.
I had to change the try/catch logic to make it work as expected after the change.
> Fixes click with scroll and multiple views

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/SomeViewsWithDifferentVisibilitesActivity.java
- sample/src/main/res/layout/activity_main.xml
- sample/src/main/res/values/strings.xml
This PR includes `assertHasFocus` and `assertHasNotFocus` as requested on the issue #95
The EditTexts used to test the two new assertions have been added to the SomeViewsWithDifferentVisibilitesActivity.
I am not sure if it's the best place as it talks about visibility, but I thought it's not worth to add a new Activity just to add this two tests.
> Add focus assertions

- library/src/main/java/com/schibsted/spain/barista/rule/BaristaRule.java
- library/src/main/java/com/schibsted/spain/barista/rule/flaky/AllowFlaky.java
- library/src/main/java/com/schibsted/spain/barista/rule/flaky/FlakyActivityTestRule.java
- library/src/main/java/com/schibsted/spain/barista/rule/flaky/FlakyTestRule.kt
- library/src/main/java/com/schibsted/spain/barista/rule/flaky/Repeat.java
- library/src/main/java/com/schibsted/spain/barista/rule/flaky/internal/FlakyStatementBuilder.java
- library/src/test/java/com/schibsted/spain/barista/rule/flaky/FlakyStatementBuilderTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/FlakyTestRuleTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ViewPagerTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ViewPagerWithoutIdTest.java
Solves #131
This change decouples FlakyTestRule from ActivityTestRule. We prefer composition over inheritance for rules.
I left the FlakyActivityTestRule as deprecated. Even though we're moving to Barista 2.0 with breaking changes, this one has a really low cost to maintain. We'll remove it in the future, reducing the migration impact for Barista 2.0.
>  Create FlakyTestRule independent from ActivityTestRule

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
Add assertion 
`assertText(R.id.widget, "expected text")`
This assertion was requested on issue #120
>  Add assertText assertion to check that a given text is shown in a given View

- MIGRATION-2.0.md
- README.md
We're almost there! I updated the readme with the recent changes and wrote a migration guide for 2.0 with detailed breaking changes from 1.x.
In the readme, I've put the download section at the top to make it easier to copy&paste.
I did it incrementally, so I might have missed something. Please take a look:
- [Migration guide](https://github.com/SchibstedSpain/Barista/blob/readme2/MIGRATION-2.0.md)
- [New readme](https://github.com/SchibstedSpain/Barista/blob/readme2/README.md)
> Readme for 2.0

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
At some point, we loosed this assertion, so here it is again!
Fixes #178 
The README.md seems to be right, so no need to touch it! 🎊
> Add assert not displayed with text (again) 

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/FailureHandlerTest.java
While developing on https://github.com/Sloy/android-screenshot-reporter, which uses a FailureHandler to take screenshots on errors, I realised that the magic in assertDisplayed method wasn't behaving as expected.
**How should it work:**
When you call `assertDisplayed(id|text)` and the condition doesn't match -> you should receive **one and only one** error in your global Espresso's FailureHandler. Either the default `DefaultFailureHandler` or your own setted with `Espresso.setFailureHandler(custom)`. 
That happens thanks to `SpyFailureHandler.resendFirstError(...)`.
**How is it working now:**
When you call `assertDisplayed(id|text)` and the condition doesn't match -> The exception is simply thrown and your FailureHandler doesn't get notified.
The cause was a wrong logic on the try/catch …
> Fixes wrong error handling on assertDisplayed

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaBackgroundAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaCheckedAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaEnabledAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaFocusedAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaHintAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaImageViewAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/AssertAny.kt
- library/src/main/java/com/schibsted/spain/barista/internal/MagicAssert.kt
- library/src/main/java/com/schibsted/spain/barista/internal/util/ResourceType.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
This method allows asserting that any view on the screen matches a certain condition, without getting the infamous Espresso error `AmbiguousViewMatcherException`.
We say we do magic for things like views below a scroll or duplicated views on screen. But actually that only work for some Assertions and Interactions, not all of them implement it. E.g.: https://github.com/SchibstedSpain/Barista/issues/107 https://github.com/SchibstedSpain/Barista/issues/46
In this PR I propose to extract the assertion code to one place, and reuse it everywhere it's needed. (The same should be done for Interactions, see https://github.com/SchibstedSpain/Barista/pull/196).
I created a function to be used like this:
```kotlin
assertAnyView(withId(R.id.button), isDisplayed())
```
We don't usually expose kotlin …
> Introduce generic assertAnyView function

- README.md
As soon as I saw #219 issue, I thought that the simpler way to fix it is to link it on the readme. In that issue, @FireZenk explains how to deal with `@Rule` on Kotlin, giving good examples. Right now, I think we don't need to explain how to use Barista as a `@Rule` on Kotlin, as it's used as every other `@Rule` ... but linking the issue is easy enough to be done.
> Explain how to use @get:Rule in Kotlin tests

- README.md
The old androidTestCompile is deprecated. We should recommend using the new androidTestImplementation.
I also updated the google repository configuration, assuming people use the 3.x Android Gradle plugin.
Fixes https://github.com/SchibstedSpain/Barista/issues/217
> Update readme with new Gradle syntax

- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaListInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/failurehandler/SpyFailureHandler.kt
- library/src/main/java/com/schibsted/spain/barista/internal/viewaction/ClickChildAction.java
- sample/build.gradle
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsChildClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/util/FailureHandlerValidatorRule.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/util/SpyFailureHandlerRule.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/util/SpyFailureHandlerRuleTest.kt
The error handling of clickListItem and clickListItemChild were not great. This is part of https://github.com/SchibstedSpain/Barista/issues/239
Basically:
1. We were not notifying Espresso's FailureHandler when the methods fail
2. The exception messages don't provide good info about what went wrong.
I improved the tests with AssertJ's `catchThrowable()`, and a new `SpyFailureHandlerRule` similar to `FailureHandlerValidatorRule` but with less unpredictable magic.
This way we make sure that 
1. The Espresso's FailureHandler is invoked only once or never, depending on the test case.
2. The Exception message gives the information we expect, and we don't accidentally break it in the future.
PS: I added Java 8 support to the sample project, so we can use lambdas in the tests for:
```java …
```
> Fix ListInteractions failure handling

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/AssertAny.kt
- library/src/main/java/com/schibsted/spain/barista/internal/matcher/BooleanMatcher.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertAnyTest.kt
```kotlin
assertAny<EditText>(R.id.edittext) {
it.text.toString() == "Hello!"
}
```
Now, we can use this new `assertAny` method in kotlin, and inside the lambda, return a `boolean`:D
This method(s) will help to create custom assert for any view without know how to build *matchers*
> Add assertAny {} with sugar for kotlin

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/matcher/BooleanMatcher.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertAnyTest.kt
I misunderstood the purpose of the `message` parameter when reading the implementation of #254, so here's a rename to make the parameter autoexplainative.
> Rename custom assertion `message` parameter to better explain its intention

- README.md
Hello from South Korea! 🌏
#254 is a great PR, but I needed to read its code twice to understand what it was offering. The readme didn't explain the whole power of the new feature.
This PR will try to better explain it. Feel free to improve it as much as possible. I tried to focus on newbies instead of Espresso experts because that's what I am 🤗
By the way, if I misunderstood the API that was offered, feel free to shame on me 💩and commit on this PR without previous notice.
> Improve the explanation about custom assertions

- index.html
The original link in the docs is broken. The file changed name from `…2.0.md` to only `…2.md`
> Updating link to Migration file

- README.md
As @Sloy explained at #255, the agreed readme could be improved. This PR does it.
Now, the project's readme will explain the custom assertion message feature by example.
> Clarify how to use the custom assertions message

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaListAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListViewAssertionTest.kt
Fixes bug that caused all calls to `assertListItemCount` to succeed.
Added test for this use case.
> Fix assertListItemCount not throwing error when failed bug

- README.md
- config/androidstudio/codestyle/BaristaAndroid.xml
- config/androidstudio/codestyle/SchibstedAndroid.xml
- config/androidstudio/install-codestyle.sh
I copied our internal code style settings, based on Square and adapted for the Android's official Kotlin style guide.
Also added a little paragraph in the readme about contributing and how to install the code style.
Is this enough? Should we add or change anything else?
Fixes https://github.com/SchibstedSpain/Barista/issues/154
> Add Schibsted code style

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/assertion/VisibilityAssertionsTest.java
- sample/src/main/res/layout/activity_main.xml
Related to #224 
This is also a subset of: #266
Adds 2 new methods for BaristaVisibilityAssertions that allows users to assertTheVisibility of anything using Espresso Matchers.
*Next steps* Add other methods to check the existence of views using Matchers (assertExist/assertNotExist)
> Adds assertVisible(Matcher) and assertNotVisible(Matcher) methods

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaClickableAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/main/res/layout/activity_main.xml
Adds `BaristaClickableAssertions`, which implements the methods `assertClickable` and `assertNotClickable`. The README was updated accordingly.
**Tests:**
Relevant tests were added to the `AssertionsTest` Java class.
I have used the existing Button views in `SomeViewsWithDifferentVisibilitiesActivity`, adding the property `clickable` to them; let me know if new views are preferred/needed.
> Add BaristaClickableAssertions

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/main/res/values/strings.xml
This PR is for feature request #292 
- added `assertContains()` & `assertNotContains()` methods with string resource id
- updated tests
- updated readme
> added support for string resource id in contains assertion

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssistiveTextAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaHelperTextAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/HelperTextTest.kt
- sample/src/main/res/layout/activity_hintanderrortext.xml
- sample/src/main/res/values/strings.xml
This commit will add new assertion for TextInputLayout's helper text 
- Created feature request: https://github.com/SchibstedSpain/Barista/issues/302
- Implemented a new class for asserting the helper text from the TextInputLayout
- Added Android tests to demonstrate the behaviour
- Added example to an existing layout file activity_hintanderrortext.xml
- Updated README for documentation for implementation details
> Assertion for TextInputLayout Text Helper Hint

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssistiveTextAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaContentDescriptionAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ContentDescriptionTest.kt
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/ContentDescriptionActivity.kt
- sample/src/main/res/layout/activity_content_description.xml
- sample/src/main/res/values/colors.xml
- sample/src/main/res/values/strings.xml
This PR tries to fix: https://github.com/SchibstedSpain/Barista/issues/304
Add content description assertion, working on images, texts... any view :D
> Assert content description

- .travis.yml
Travis builds were failing to download jdk 8
It was caused by using `xenial` ubuntu distribution.
Failed build: https://travis-ci.org/SchibstedSpain/Barista/builds/565832037
Moved to `trusty` seems to fix it
https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/6
> Use openJdk

- README.md
You could add in the AndroidX excludes as well, but it seemed like it was going to make this pretty complicated in onboarding instructions, and not everyone uses those androidx packages.  This is what you could add:
```
exclude group: 'androidx.annotation'
exclude group: 'androidx.legacy'
exclude group: 'androidx.recyclerview'
exclude group: 'androidx.vectordrawable'
```
*Dependencies*
* Old version with support library: https://mvnrepository.com/artifact/com.schibsted.spain/barista/2.10.0
* This version with Android X: https://mvnrepository.com/artifact/com.schibsted.spain/barista/3.2.0
> Removed `exclude group: 'com.android.support'`

- README.md
It's just a way to keep a style and ease glancing at the readme
> Use always the id list in the example

- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaScrollInteractions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ScrollsTest.java
This is quite convenient when we have UI structure a bit more complex than a unique ID/string.
> Add scrollTo signatures to support scrolling on custom view matcher.

- README.md
Right now, we're only showing the method that mocks the camera. But we don't share that the user also has to use a specific rule. This PR fixes it.
BTW, totally open to comments and suggestions.
> Better explain how to mock the camera

- README.md
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaMenuClickInteractions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuClickTest.java
Added function to open the overflow menu without clicking any item, as requested on #331
> Add open overflowMenu action

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/matcher/TextStyleableColorMatcher.kt
- sample/build.gradle
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ColorsSecondaryTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ColorsTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/ColorsSecondActivity.java
- sample/src/main/java/com/schibsted/spain/barista/sample/widget/SampleCustomView.kt
- sample/src/main/res/color/secondary_selector_default_disabled_checked.xml
- sample/src/main/res/layout/activity_color.xml
- sample/src/main/res/layout/activity_color_second.xml
- sample/src/main/res/layout/sample_custom_view.xml
- sample/src/main/res/values/attrs.xml
- sample/src/main/res/values/styles.xml
Add ability to get color for `assertTextColorIs` from styleable and style resource:
``` kotlin
assertTextColorIs(
R.id.customTextView,
R.styleable.SampleCustomView,
R.style.SampleCustomStyle,
R.styleable.SampleCustomView_customColor
);
```
This way, if text color is not matching the color defined in the property `customColor`of `SampleCustomStyle` it will fail
> Feature: Add color styleable assertTextColorIs

- library/src/main/java/com/schibsted/spain/barista/rule/cleardata/ClearDatabaseRule.kt
- library/src/main/java/com/schibsted/spain/barista/rule/cleardata/internal/DatabaseOperations.kt
- library/src/test/java/com/schibsted/spain/barista/cleardata/ClearDatabaseRuleTest.java
- Provide Room metadata table name and method to exclude it from DB clearing process
- Implement test case: `doesNotDeleteRoomMetadata`
- Replace deprecated method: `InstrumentationRegistry.getTargetContext()`
Room has become the most popular ORM library and it is officially supported by Google Android team. This library creates and populates automatically a table with important database metadata: identity hash of our implemented database schema. If this metadata is deleted it can cause unexpected behavior or even crashes (`IllegalStateException`).
For more info see:
[Understanding migrations with Room](https://medium.com/androiddevelopers/understanding-migrations-with-room-f01e04b07929)
[How does Room verify data integrity](https://stackoverflow.com/questions/57547129/how-does-room-verify …
> Exclude Room metadata when clearing DB

- library/build.gradle
Hi, I confronted the following error while building with barista and an internal company's library.
> Duplicate files copied in APK META-INF/library_release.kotlin_module
And found out that barista is taking this name too:
I've already fixed on our side but think this could be useful for other barista users.
------
This PR has as purpose avoid taking the name of the current folder to generate the
kotlin_module generated into the .aar/META-INF.
In practice, rename "META-INF/library_release.kotlin_module" to
"META-INF/barista.kotlin_module".
This avoid Barista consumers to exclude this file if another library
generated the same one.
See: https://stackoverflow.com/q/4450960
> Change .kotlin_module generated name

- README.md
> Move the assertions tricky feature to the end of the list

- .github/FUNDING.yml
I just learned we can use custom links for the Sponsor button in GitHub!
So we can link to our "Thank you Barista " issue. We don't want money, just "thank you" notes :) 
Here's more info about the button: https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository
> Add Sponsor button linking to our "Thank you" post

- gradle.properties
- library/build.gradle
- sample/build.gradle
This library doesn't depend on any android support library (except glide, that it's just used in the sample app and I updated it). So we can remove jetifier safely and get faster builds 🎉.
I needed to update `mockito-android` because when I removed jetifier mockito start complaining about "final interfaces". The ways of ~the lord~ mockito are inscrutable.
BTW: there are two tests failing at `master` right now and they fail in this PR too: `checkColorList_whenDisabled` and `checkColorList_whenChecked`.
> Remove Jetifier

- library/src/main/java/com/schibsted/spain/barista/internal/matcher/TextColorMatcher.kt
Thanks to @BraisGabin on #350 that pointed out that `checkColorList_whenDisabled` and `checkColorList_whenChecked` tests were failing.
I've investigated and found that on API 22 color state was not returning the same instance, (I believe android does some caching in future versions).
So I've moved color state list check to verify all possible states of color state list instead of checking for the same instance.
> Fix: Color state list now checks all possible states

- library/src/main/java/com/schibsted/spain/barista/internal/matcher/TextColorMatcher.kt
As @rocboronat points on #351 : https://github.com/AdevintaSpain/Barista/pull/351#discussion_r431833434
It's not clear what `"-"` does, so I've extracted states to a method and commented with link to stack overflow
> Update disabled states for color state list

- .github/workflows/main.yml
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuClickTest.java
From https://github.com/AdevintaSpain/Barista/issues/333
Add Github actions CI to run instrumentation tests on  every push on master and PR
> Entry point on github actions

- .github/workflows/main.yml
I've seen some really weird test failures in our project when using API 29.
I'm not sure that they are also happening here, but since tests are failing so much in the _experimental_ CI with Github Actions, it's worth trying a downgrade to API 28.
> Downgrade emulator version for better stability

- sample/src/androidTest/java/com/schibsted/spain/barista/sample/FlakyTestRuleTest.java
Using a random is not an ideal way to test the flaky rule. Because, once in a while, the randomness will make the test fail. 
I replaced the random condition with a static boolean, that is shared between test repetitions. That way it's easier to deterministically make the test fail the first time only.
This should avoid some test failures that I've seen on CI
> Make FlakyRule tests less flaky

- .travis.yml
- README.md
- build.gradle
- library/src/main/java/com/schibsted/spain/barista/interaction/PermissionGranter.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/PermissionGranterTest.kt
Updated permission granter to match ANY of the allow buttons in this order:
```kotlin
"com.android.permissioncontroller:id/permission_allow_foreground_only_button",
"com.android.permissioncontroller:id/permission_allow_button",
"com.android.packageinstaller:id/permission_allow_button"
```
So we make sure that one of this buttons exists on the permission dialog.
Also, added `allowPermissionOneTime` that accepts permission just this time, so we can do tests that involves multiple permission request time
One time permissions: https://developer.android.com/guide/topics/permissions/overview#one-time
> Feature: Update PermissionGranter to allow android 11 permissions

- library/src/androidTest/java/com/schibsted/spain/barista/internal/util/BitmapComparatorTest.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaErrorAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaHintAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaListInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaMenuClickInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/util/ResourceType.kt
- library/src/main/java/com/schibsted/spain/barista/rule/cleardata/ClearPreferencesRule.java
- library/src/main/java/com/schibsted/spain/barista/rule/cleardata/internal/FileOperations.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListViewAssertionTest.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsChildClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsScrollTest.java
- Using ApplicationProvider.getApplicationContext() instead of getTargetContext()
Replacing getTargetContext() with ApplicationProvider.getApplicationContext() as stated in the deprecated info.
```
/**
* Return a Context for the target application being instrumented. Use this to get a {@link
* Context} representing {@link Instrumentation#getTargetContext()} into your test.
*
* @deprecated use {@link androidx.test.core.app.ApplicationProvider#getApplicationContext()}
*     instead.
*/
@Deprecated
public static Context getTargetContext() {
return getInstrumentation().getTargetContext();
}
```
> getTargetContext() #352 Replace Context Deprecated

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaErrorAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/HintAndErrorTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/HintAndErrorActivity.java
- sample/src/main/res/layout/activity_hintanderrortext.xml
When playing with errors... we have a method to check for `assertError` , error is displayed...
But, we didn't had a method to check for error is not shown...
> Add assertNoError method side of assertError methods

- .travis.yml
As we have a github action that builds the code, is no need to have it already on travis
> Remove travis master builds

- library/src/main/java/com/schibsted/spain/barista/rule/flaky/FlakyTestRule.kt
- library/src/main/java/com/schibsted/spain/barista/rule/flaky/internal/FlakyStatementBuilder.java
- library/src/test/java/com/schibsted/spain/barista/rule/flaky/FlakyStatementBuilderTest.java
In this PR I've added a method that allows users to set repeat attempts by default, it works the same way than `allowFlakyAttemptsByDefault` but applies the `@Retry` annotation to all methods
> Implemented repeat attempts by default

- README.md
It gives a 404. So ugly. Do we have to replace it with anything? I think not, but asking is always safer 😄
> Remove Bintray's badge

- library/src/main/java/com/schibsted/spain/barista/internal/matcher/DrawableMatcher.kt
- sample/build.gradle
- sample/src/main/res/layout/activity_main.xml
Hello all,
We are using Barista and recently something caught our attention: some of our tests (API 23) where failing.
Turns out it was the way drawables are handled.
This project minSDK is 19, which means (by the way of [official docs](https://developer.android.com/guide/topics/graphics/vector-drawable-resources)) that we need to use a back compat solution. Even when considering API 23, [VectorDrawableCompat](https://developer.android.com/reference/androidx/vectordrawable/graphics/drawable/VectorDrawableCompat) docs states that `For API 24 and above, this class delegates to the framework's VectorDrawable. For older API version, this class lets you create a drawable based on an XML vector graphic.` - using a compat solution would still be needed.
Let me know whatever is needed to get this …
> Add support to vector drawable using AppCompat

- README.md
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaEditTextInteractions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/EditTextTest.java
- sample/src/main/res/layout/activity_edittext.xml
* Add a new `typeTo()` Text Interaction in `BaristaEditTextInteractions`. It's similar to `writeTo()`, but it uses Espresso's `typeText()` instead of `replaceText()`.
* Add KotlinDoc/JavaDoc to the Text Interaction methods, for users to tell the difference between `writeTo()` and `typeTo()`.
--------
* Add 3 new constrained `EditTexts` to the layout, for UI unit tests of `typeTo()`
* The `EditTexts` have maxLength of 10 characters, and don't allow spaces, and only allow ASCII text or digits 0-9
* More info about `EditText` filters: https://stackoverflow.com/questions/33993041/android-disable-space-only-for-edittext
--------
* Check that `typeTo()` will constrain and limit the typed characters to ASCII and digits 0-9, as per the EditText `digits` attribute.
* Check that `typeTo()` will …
> Fix Issue #395: Add BaristaEditTextInteractions.typeTo()

- build.gradle
- config/android-quality.gradle
- gradle/wrapper/gradle-wrapper.properties
- library/build.gradle
- sample/build.gradle
- Updated Gradle 7
- Updated Kotlin 1.4
- Removed Jacoco task because of incompatibility. And we're not using it anyway.
- Removed Novoda bintray plugin. It's not compatible with newer versions of Gradle and AGP, and we can no longer publish to JCenter. We will have to reimplement the publishing for mavenCentral.
> Update Gradle and AGP

- .github/workflows/main.yml
- sample/build.gradle
This PR enables the Android Test Orchestator in the library. It should improve the stability of tests on CI.
> Enable Orchestrator for CI

- .github/workflows/main.yml
We have 2 actions, one for the build and another for running instrumentation tests.
Right now, the instrumentation action waits for the build to finish first. It takes about 2 minutes. But there's no need for that, really. There's no dependency between them or any reused output. So we could save 2 minutes by starting the instrumentation build as soon as possible.
> Parallelise Github actions

- README.md
This PR makes the readme keep the same writing style to let the Barista newcomer focused on the content instead of the shape of the message.
> Keep the "or not?" style in the checkbox interactions section

- CONTRIBUTING.md
Let's implement [the lovely contributing file thing](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors)
> Create the contributing file

- settings.gradle
[Gradle Scans](https://scans.gradle.com/#gradle) provide a lot of information about the build. This can help us find issues, check build times, task cacheability, performance issues, etc.
It's free, so... let's add them!
https://scans.gradle.com/s/ticd5otgj47ea
The link to the Scan is published at the end of the Gradle build. In CI, you can see it in the Action logs:
> Enable Gradle build scans

- README.md
This PR fixes issue #403 by removing the list assertions from the interactions section and moving them to a better place.
> Move list assertions to a more appropriate place

- library/src/main/java/com/schibsted/spain/barista/interaction/PermissionGranter.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/PermissionGranterTest.kt
- sample/src/main/AndroidManifest.xml
In some cases we also need to test the app's behavior when the user denies a permission. This change adds the denyPermissions() method.
> Add method for denying permissions

- README.md
While preparing for the Maven Central migration [I replaced the package name and dependency coordinates](https://github.com/AdevintaSpain/Barista/pull/423) of the library. But this led to broken download instructions in the Readme! (See https://github.com/AdevintaSpain/Barista/issues/425) 
I'm adding some clarification about the different versions of Barista published in different places with different names. 
We should update the Maven Central instructions once the migration is complete. In the meantime, we should allow people to use the old dependency.
Fixes https://github.com/AdevintaSpain/Barista/issues/425
> Update Readme about the new dependency coordinates

- README.md
Was a bit confusing, but after checking the release note I managed to get the new dependency working without jcenter. Was just a small miss in the readme I think. Nice work!
> Fix readme for new artifact name

- library/src/main/java/com/adevinta/android/barista/assertion/BaristaListAssertions.kt
- library/src/main/java/com/adevinta/android/barista/assertion/BaristaVisibilityAssertions.kt
- library/src/main/java/com/adevinta/android/barista/interaction/BaristaKeyboardInteractions.kt
- library/src/main/java/com/adevinta/android/barista/interaction/BaristaListInteractions.kt
- library/src/main/java/com/adevinta/android/barista/internal/matcher/DisplayedMatchers.java
- library/src/main/java/com/adevinta/android/barista/internal/viewaction/SwipeActions.kt
- sample/src/androidTest/java/com/adevinta/android/barista/sample/BaristaRuleActivityTest.java
- sample/src/androidTest/java/com/adevinta/android/barista/sample/ListViewAssertionTest.kt
- sample/src/androidTest/java/com/adevinta/android/barista/sample/assertion/VisibilityAssertionsTest.java
> Rewrite hamcrest internal API usage 

- gradle.properties
- library/build.gradle.kts
- scripts/publish-module.gradle
When we updated our release process to work with sonatype, we had to add `libArtifact` to **gradle.properties**, but that not allowed us to deploy different modules to maven central.
This PR allows us to have different modules, so we can deploy #439 (barista-compose) someday!
> Tech: Get name for artifact from each module

- README.md
It wasn't that reliable to test things on emulators. So now that we backed to pass the tests locally again, let's just remove the badge.
> Remove the CI badge because the test environment is flaky

- .github/workflows/main.yml
Update test emulators to run on APIs 26 and API 31 (Android 12), so we can start updating this library to android 12...
> Tech: Add api 31 to test

- .github/workflows/main.yml
- sample/build.gradle.kts
Following the dependencies page for android test i found that version 1.4.1 of orchestarator fixes the API 31 problem! YAY!
https://developer.android.com/jetpack/androidx/releases/test#orchestrator-1.4.1
> Fix: API 31 run tests
