AdevintaSpain/Barista

- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ViewPagerTest.java
Let's merge this PR and put it's code into #5 to avoid the flakiness of swipeBack. If the tests pass, then we could merge #5.
> Repeat the pager tests ten times in order to reproduce their flakiness

- README.md
Issue : https://github.com/SchibstedSpain/Barista/issues/4
> add download dependency to README.md

- README.md
I added the gradle dependency to the readme for easier copy&paste
> Changed scope of gradle dependency on the README

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaSleepActions.java
- library/src/main/java/com/schibsted/spain/barista/custom/SleepViewAction.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/SleepTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaActions.java
This is related with #18 
We learnt it here: https://youtu.be/isihPOY2vS4?t=11m25s
> Add an elegant way to do a Thread.sleep()

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaRecyclerViewActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/RecyclerViewTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaActions.java
- sample/src/main/java/com/schibsted/spain/barista/sample/RecyclerViewActivity.java
- sample/src/main/res/layout/row_textview.xml
scroll to a position in a recyclerView
> Add a recycler view test method scrolls to a position

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaAssertions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/EditTextTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaAssertions.java
- sample/src/main/res/layout/activity_edittext.xml
- sample/src/main/res/values/strings.xml
It implements the solution of #36 . Thanks @jose-casado for requesting the feature!
> Assert that an EditText has a hint

- README.md
I forgot to introduce them :·/
> Introduce clickRecyclerViewItemChild to README.md

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaAssertions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaAssertions.java
- sample/src/main/res/layout/activity_main.xml
- sample/src/main/res/values/strings.xml
> Added assertions for isChecked and isUnchecked

- README.md
Related with #7 
Waiting for #51
> Introduce Barista's considerations that speed up the testing development

- README.md
The readme was a mix between a proposal I made in a PR, and some @Sloy feedback. But was a strange mix. This PR fixes it, using my not-so-great English powers 🇬🇧 
@Sloy , feel free to merge it if you approve it, in order to keep the PR's list clean :tada:
> Improve the magic section of the readme

- sample/src/androidTest/java/com/schibsted/spain/barista/sample/FlakyRuleTest.java
Before this PR, the test class that checks the `FlakyActivityTestRule` is called `HelloWorldActivityTest`. That doesn't help understanding what it checks.
This PR also renames the test methods to match the project's default
> Rename the test of the FlakyRule to explain what it does

- README.md
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/introduction/IntroducingBaristaAssertions.java
Just small changes to make the readme sexier.
> Improve README.md with little style

- library/src/main/java/com/schibsted/spain/barista/BaristaMenuClickActions.java
- library/src/main/java/com/schibsted/spain/barista/custom/DisplayedMatchers.java
- library/src/main/java/com/schibsted/spain/barista/custom/HelperMatchers.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuClickActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuSupportActionBarClickTest.java
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/MenuActivity.java
- sample/src/main/java/com/schibsted/spain/barista/sample/MenuSupportActionBarActivity.java
- sample/src/main/res/layout/activity_menu.xml
- sample/src/main/res/menu/actions_menu.xml
Added menu click actions.
This pr tries to fix: https://github.com/SchibstedSpain/Barista/issues/72
* Add `BaristaMenuClickActions`
* Add actions to click by ID
* Add actions to click by Text
* Add options inside click methods, for `Overflow items`
> Add menu click

- .travis.yml
- library/src/main/java/com/schibsted/spain/barista/ci/IgnoreContinousIntegration.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/FlakyRuleTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/MenuSupportActionBarClickTest.java
Another way to implement #80 
In this case, we just add some noise to Travis log with the flags `--stacktrace --info`. This should make that Travis don't kill our process due to not writing into the log.
> Run Espresso tests on Travis

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaClickActions.java
- library/src/main/java/com/schibsted/spain/barista/custom/DisplayedMatchers.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ClickTest.java
As issue:  [#71](https://github.com/SchibstedSpain/Barista/issues/71) points, we cannot click on a view wusing `R.sting.xxx` resources.
This PR fixes it!
> Add feature: Click by string resource

- README.md
> Fix cleared file directories on README.md

- README.md
I hope that @Sloy will like this PR. Sorry for my lack in English! :gb:
> Avoid the lovely "cos" word

- build.gradle
- library/build.gradle
- sample/build.gradle
Welcome to the futu... Oh wait! To the presenter! 🍷
> Add Kotlin to Barista! :tada:

- library/src/main/java/com/schibsted/spain/barista/cleardata/ClearDatabaseRule.kt
- library/src/test/java/com/schibsted/spain/barista/cleardata/ClearDatabaseRuleTest.java
This change adds a method to the rule that let's the user exclude tables matching a certain regular expression.
Useful for integration tests where some tables on the database are expensive to refill, and aren't modified between tests. Like static information.
> Allow excluding tables from the ClearDatabaseRule

- library/src/main/java/com/schibsted/spain/barista/BaristaClickActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/LongClickTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/FlowFirstScreen.java
I added the possibility to interact with a view by using a long press viewactions.
Tests were also added to make sure the long press action is working correctly.
> Added LongClickActions

- build.gradle
- library/src/main/java/com/schibsted/spain/barista/internal/util/BitmapComparator.kt
Upgrade kotlin to 1.1.51 and make BitmapComparator internal.
Related to #124
> Make BitmapComparator internal

- README.md
- library/src/main/java/com/schibsted/spain/barista/BaristaScrollActions.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ScrollsTest.java
> Add the scrollTo(R.string.text) method pointing to Barista 1

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
This PR will fix issue #164 opened when discussing on the PR #163
> Add assert not displayed

- README.md
Let's avoid hurting readers eyes 👁‍🗨 👁
> Keep the readme style to introduce API methods

- README.md
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaScrollInteractions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ScrollsTest.java
We don't know what happened with #169, so... let's repeat it.
> Add the scrollTo(R.string.text) method

- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaClickInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaListInteractions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsChildClickTest.java
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListsClickTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/ListsActivity.java
- sample/src/main/res/values/ids.xml
Issue https://github.com/SchibstedSpain/Barista/issues/187
> Added support for GridView interactions

- README.md
> Fix the "not" section of the text color asserts

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaListAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaListInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/matcher/ListViewItemCountAssertion.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListViewAssertionTest.kt
Created class BaristaListAssertions to hold list and recyclerview assertions.
These assertions allow the finding of an item in a recycler or list view
> Created class BaristaListAssertions 

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/matcher/BooleanMatcher.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertAnyTest.kt
Fixes https://github.com/SchibstedSpain/Barista/issues/258
> Rename assertionErrorMessage to assertionDescription

- README.md
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaListAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ListViewAssertionTest.kt
- sample/src/main/res/values/strings.xml
Add 2 new features:
- Support textId
- Support custom assertion
I updated the `README.md` in order to explain how to use them:
```
assertDisplayedAtPosition(R.id.recycler, 0, R.string.hello_world);
assertDisplayedAtPosition(R.id.listId, 0, R.id.text_field, R.string.hello_world);
assertCustomAssertionAtPosition(R.id.recycler, 0, customViewAssertion);
```
> Add new features in BaristaListAssertions

- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaRatingBarViewInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/viewaction/RatingBarActions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/SeekBarTest.java
- sample/src/main/java/com/schibsted/spain/barista/sample/SeekBarActivity.java
- sample/src/main/res/layout/activity_seekbar.xml
`RatingBar` is a subcomponent of `AbsSeekBar` but it works with its own methods (instead of `progress` it uses `rating`)
> Add RatingBar barista methods

- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaVisibilityAssertions.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/assertion/VisibilityAssertionsTest.java
- sample/src/main/res/values/strings.xml
As requested on #286 I've added the assertNotDisplayed assertion using a view Id and a String resource.
> Add assertNotDisplayed assertion with view id and string resource

- README.md
Added the missing displayed not displayed assertions using both view ID and String resource
> Add missing displayed examples

- README.md
Let's use the same naming everywhere
> Use this_style instead of thisStyle as ids in the readme

- library/build.gradle
- library/src/main/java/com/schibsted/spain/barista/BaristaChipAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/assertion/BaristaChipAssertions.kt
- library/src/main/java/com/schibsted/spain/barista/interaction/BaristaChipInteractions.kt
- library/src/main/java/com/schibsted/spain/barista/internal/viewaction/ChipViewActions.kt
- sample/build.gradle
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/ChipsTest.kt
- sample/src/main/AndroidManifest.xml
- sample/src/main/java/com/schibsted/spain/barista/sample/CameraActivity.kt
- sample/src/main/java/com/schibsted/spain/barista/sample/ChipsActivity.kt
- sample/src/main/res/layout/activity_chips.xml
- sample/src/main/res/values/styles.xml
Add chip tests:
*assertAnyChipSelected*: to check a `ChipGroup` has any chip selected.
*closeChip*: Chip action to act over close icon on chip
> Add Chips functionality and test

- .github/workflows/main.yml
I saw some warnings in the workflow log, and I'm having issues with passing the test suite. Let's see how the newer version works.
Changelog https://github.com/ReactiveCircus/android-emulator-runner/releases
> Update emulator workflow

- README.md
I'm not a native speaker of English. But I believe "guy" is a gender-biased word. Even if we're used to seeing it as a generic word.
What do you think if we replace the Barista slogan with a different word to be more inclusive? 
From `The guy who serves a great Espresso`
to `The tool that serves a great Espresso`
or some other funnier thing.
Agree? Any better idea?
> Is "guy" the right word?

- library/src/main/java/com/schibsted/spain/barista/internal/matcher/DrawableMatcher.kt
- sample/src/androidTest/java/com/schibsted/spain/barista/sample/AssertionsTest.java
- sample/src/main/res/layout/activity_main.xml
Update matchesSafely implementation in Drawable Matcher class adding Material Button View.
> Tech: Add material button drawable matcher

- README.md
It's strange to talk about us as developers instead of Barista as software. Barista will do the hard job. We are drinking margaritas in an old lost paradisiac island 🍸
> Replace "we" with "Barista"

- README.md
This PR adds a subsection to the contributing section.
> Encourage collaborators to add tests written in Java

- README.md
#329 said we would introduce #323 to the readme but we never did. This PR does it.
> Introduce the custom matchers version of scrollTo to the readme

- build.gradle
Just an update... as we were using AGP 4.2.2
> Update android gradle plugin to 7.0.2

- README.md
- library/src/main/java/com/adevinta/android/barista/interaction/BaristaCheckboxInteractions.kt
- library/src/main/java/com/adevinta/android/barista/internal/viewaction/CheckableViewActions.kt
- sample/src/androidTest/java/com/adevinta/android/barista/sample/CheckboxTest.kt
Add a new interaction to check a checkbox
> Feature: check checkbox

- scripts/publish-root.gradle
Remove fake signature variables from publish-root.gradle
> Move fake secrets to local.properties

- scripts/publish-root.gradle
I'm reverting #467 here, because that change breaks the project for all of us who don't have the secrets 😅
> Revert "Move fake secrets to local.properties"

- config/androidstudio/install-codestyle.sh
Same as https://github.com/AdevintaSpain/TaggingViewer/pull/5
> Fix code style script

- barista-compose/src/androidTest/java/ComposeAssertionsTest.kt
- barista-compose/src/androidTest/java/com/adevinta/android/barista/compose/assertion/ComposeAssertionsTest.kt
- barista-compose/src/main/AndroidManifest.xml
- barista-compose/src/main/java/com/adevinta/android/barista/compose/assertion/BaristaAssertions.kt
- barista-compose/src/main/java/com/adevinta/android/barista/compose/assertion/internal/ComposeTestRuleUtils.kt
Barista compose package was wrong, sorry.
> Move compose package

- README.md
Thanks @ajburley for reporting this issue 🙇
https://github.com/AdevintaSpain/Barista/issues/504
> Don't use octal numbers
